#!/bin/sh

if [[ $(ps -ho cmd $$) != *"bash"* ]]; then
  echo "Please use bash. No other shells are supported."
elif [ -d "locked" ] || [ -d "cerrado" ]; then
  echo "Please delete the dungeon before regenerating it."
  echo "You can use \`sudo rm -rf locked visited\` but be careful."
else
  export SHELL_ADVENTURE_SCRIPTS=$PWD/scripts
  export SHELL_ADVENTURE_ROOT=$PWD
  export SHELL_ADVENTURE_LANG=${LANG:0:2}
  alias cd="source $SHELL_ADVENTURE_SCRIPTS/cd"

  nim c -o:./scripts/build_dungeon ./scripts/build_dungeon.nim
  ./scripts/build_dungeon

  if [[ $SHELL_ADVENTURE_LANG == "es" ]]; then
    sudo chown root:root ./cerrado/una_habitacion_oscura/la_habitacion_de_la_espada/espada
    roomlocked="cerrado"
    roomstart="entrada"
  else
    sudo chown root:root ./locked/a_dark_room/the_sword_room/sword
    roomlocked="locked"
    roomstart="entrance"
  fi

  clear
  for i in {1..6}; do
    sleep .5
    echo "o   
O        *pat*"
    sleep .5
    echo "    o
    O     *pat*"
  done

  pushd $roomlocked > /dev/null && \
  chmod 111 . && \
  pushd $roomstart > /dev/null && \
  source $SHELL_ADVENTURE_SCRIPTS/rooms/$roomstart.sh && \
  touch $SHELL_ADVENTURE_ROOT/visited/$roomstart
fi
