#!/bin/bash

if [ "$#" == "0" ]; then
  echo "No leaving the dungeon"
else
  pushd $@ > /dev/null 2>&1
  room_name="${PWD##*/}"
  if ! [ -f "$SHELL_ADVENTURE_ROOT/visited/$room_name" ] ; then 
      touch "$SHELL_ADVENTURE_ROOT/visited/$room_name"
      source $SHELL_ADVENTURE_SCRIPTS/rooms/$room_name.sh
  fi
fi
