#!/bin/bash

if [ $SHELL_ADVENTURE_LANG -eq "es"]; then
  trappedLine1="no puedes esCapar"
  trappedLine2="no saldrás de aquí"
  trappedLine3="ríndete"
  trappedLine4="acepta mi CONTROL"
  finalLine="cobaRde! Matame si puedes!"
else
  trappedLine1="you're trapped"
  trappedLine2="you Can't escape"
  trappedLine3="you will remain here"
  trappedLine4="i have CONTROL"
  finalLine="kill me coward! ReMove me!"
fi

trap "sleep 1; echo $finalLine" EXIT
trap "sleep 1; echo $finalLine" SIGINT

while true; do
  for i in {1..20}; do
    echo $trappedLine1
  done
  for i in {1..20}; do
    echo $trappedLine2
  done
  for i in {1..20}; do
    echo $trappedLine3
  done
  for i in {1..20}; do
    echo $trappedLine4
  done
done

